services:
  deepsproxy:
    # network_mode: host
    environment:
      - PLAYWRIGHT_REMOTE_URL=http://playwright:9301
    volumes:
      - ./src:/app/src:rw
  playwright:
    # network_mode: host
    volumes:
      - ./src:/app/src:rw
      - ./deepseek_profile:/app/deepseek_profile:rw
